feat: add functionality to set KeyDB password using env variable

diff --git a/data/services/docker-compose.yaml b/data/services/docker-compose.yaml
--- a/data/services/docker-compose.yaml
+++ b/data/services/docker-compose.yaml
@@ -11,6 +11,22 @@ services:
   # KeyDB
   keydb-main:
     container_name: keydb-main
+    entrypoint: >
+      sh -c "
+        if [ -n "$${KEYDB_MAIN_PASSWORD}" ] && [ "$${#KEYDB_MAIN_PASSWORD}" -ne 0 ]; then
+          if [ "$${#KEYDB_MAIN_PASSWORD}" -ge 96 ]; then
+            keydb-server /etc/keydb/keydb.conf --requirepass "$${KEYDB_MAIN_PASSWORD}"
+          else
+            echo 'Error: KEYDB_MAIN_PASSWORD length must be at least 96 characters.' >&2
+            exit 1
+          fi
+        else
+          keydb-server /etc/keydb/keydb.conf
+        fi
+      "
+
+    environment:
+      KEYDB_MAIN_PASSWORD: ${KEYDB_MAIN_PASSWORD}
     image: eqalpha/keydb:alpine
     ports:
       - 0.0.0.0:${KEYDB_MAIN_EXPOSE_PORT:-6379}:6379
